trigger: none

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    stages:
    - stage: Stage
      jobs:
      - job: HostJob
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
          displayName: 'Use Python'
        
        - script: |
            python -m pip install --upgrade pip
            pip install -r local-requirements.txt
            pip install -e .
            python setup.py bdist_wheel --all
          displayName: 'Install & Build'
        
        - task: EsrpRelease@4
          inputs:
            ConnectedServiceName: 'Playwright-ESRP'
            Intent: 'PackageDistribution'
            ContentType: 'PyPi'
            ContentSource: 'Folder'
            FolderLocation: './dist/'
            WaitForReleaseCompletion: true
            Owners: 'maxschmitt@microsoft.com'
            Approvers: 'maxschmitt@microsoft.com'
            ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
            MainPublisher: 'Playwright'
            DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
          displayName: 'ESRP Release to PIP'
