
trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r local-requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install -e .
  displayName: 'Install Playwright'

- script: |
    python setup.py bdist_wheel --all
  displayName: 'Build'
