
trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r local-requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install -e .
  displayName: 'Install Playwright'

- script: |
    python setup.py bdist_wheel --all
  displayName: 'Build'

- task: EsrpRelease@4
  inputs:
    ConnectedServiceName: 'Playwright-ESRP'
    Intent: 'PackageDistribution'
    ContentType: 'PyPi'
    ContentSource: 'Folder'
    FolderLocation: './dist/'
    WaitForReleaseCompletion: true
    Owners: 'maxschmitt@microsoft.com'
    Approvers: 'maxschmitt@microsoft.com'
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
    MainPublisher: 'Playwright'
    DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'