
trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r local-requirements.txt
    pip install -e .
    python setup.py bdist_wheel
    python -m playwright install --with-deps
    python setup.py bdist_wheel
  displayName: 'Install dependencies'
