name: Upload Docker Image
on: [push]
jobs:
  deploy-docker:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: ${{ github.repository_owner }}/playwright-python:python-${{ matrix.python-version }}-${{ github.ref }}
        build-args: python_image_version=${{ matrix.python-version }}
