name: Upload Docker Image
on: [push]
jobs:
  deploy-docker:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: false
        tags: ${{ github.repository_owner }}/playwright-python:python-${{ matrix.python-version }}-${{ github.sha }}
        build-args: python_image_version=${{ matrix.python-version }}
    - name: Test docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: ${{ github.repository_owner }}/playwright-python:python-${{ matrix.python-version }}-${{ github.sha }}-tests
        build-args: python_image_version=python-${{ matrix.python-version }}-${{ github.sha }}
    - name: Deloy docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: ${{ github.repository_owner }}/playwright-python:python-${{ matrix.python-version }}-${{ github.sha }}
        build-args: base_version=${{ matrix.python-version }}
