name: Upload Python Package
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  deploy-conda:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: ubuntu-latest
            target-platform: linux-aarch64
          - os: windows-latest
            target-platform: win-64
          - os: macos-latest-large
            target-platform: osx-64
          - os: macos-latest-xlarge
            target-platform: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge
      - name: Prepare
        run: conda install anaconda-client conda-build conda-verify
      - name: Build and Upload
        run: |
          conda config --set anaconda_upload yes
          if [ "${{ matrix.target-platform }}" == "osx-arm64" ]; then
            conda build . -m conda_build_config.yaml -m conda_build_config_osx_arm64.yaml
          elif [ "${{ matrix.target-platform }}" == "linux-aarch64" ]; then
            conda install cross-python_linux-aarch64
            conda build . -m conda_build_config.yaml -m conda_build_config_linux_aarch64.yaml
          else
            conda build . -m conda_build_config.yaml
          fi
